"""empty message

Revision ID: 1ff46c28aae5
Revises: 0d61c62e5c52
Create Date: 2020-04-20 11:37:52.762360

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1ff46c28aae5'
down_revision = '0d61c62e5c52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('u_teams',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(('team_id',), ['teams.id'], ),
    sa.ForeignKeyConstraint(('user_id',), ['users.id'], )
    )
    op.add_column('teams', sa.Column('check_e', sa.TIME(), nullable=True))
    op.add_column('teams', sa.Column('check_s', sa.TIME(), nullable=True))
    op.add_column('teams', sa.Column('desc', sa.String(length=64), nullable=True))
    op.add_column('teams', sa.Column('name', sa.String(length=16), nullable=True))
    op.create_unique_constraint(None, 'teams', ['name'])
    op.drop_constraint('teams_ibfk_1', 'teams', type_='foreignkey')
    op.drop_column('teams', 'member_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('member_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('teams_ibfk_1', 'teams', 'users', ['member_id'], ['id'])
    op.drop_constraint(None, 'teams', type_='unique')
    op.drop_column('teams', 'name')
    op.drop_column('teams', 'desc')
    op.drop_column('teams', 'check_s')
    op.drop_column('teams', 'check_e')
    op.drop_table('u_teams')
    # ### end Alembic commands ###
