"""empty message

Revision ID: 38eadfb76420
Revises: 1ff46c28aae5
Create Date: 2020-04-21 20:38:00.321743

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '38eadfb76420'
down_revision = '1ff46c28aae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_users',
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(('team_id',), ['teams.id'], ),
    sa.ForeignKeyConstraint(('user_id',), ['users.id'], )
    )
    op.drop_table('u_teams')
    op.add_column('teams', sa.Column('leader', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'leader')
    op.create_table('u_teams',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('team_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(('team_id',), ['teams.id'], name='u_teams_ibfk_1'),
    sa.ForeignKeyConstraint(('user_id',), ['users.id'], name='u_teams_ibfk_2'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('t_users')
    # ### end Alembic commands ###
