"""empty message

Revision ID: 696291d72caf
Revises: 4f8ec1884351
Create Date: 2020-05-30 21:53:20.931215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '696291d72caf'
down_revision = '4f8ec1884351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(length=32), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(('team_id',), ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_end'), 'schedules', ['end'], unique=False)
    op.create_index(op.f('ix_schedules_start'), 'schedules', ['start'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedules_start'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_end'), table_name='schedules')
    op.drop_table('schedules')
    # ### end Alembic commands ###
