"""empty message

Revision ID: 6fdcfe3bb7b7
Revises: c7bfe06c3192
Create Date: 2020-05-29 20:58:44.361318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fdcfe3bb7b7'
down_revision = 'c7bfe06c3192'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
