"""empty message

Revision ID: b3e89abf61f3
Revises: f8c29d3ca28e
Create Date: 2020-06-19 21:22:51.198234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3e89abf61f3'
down_revision = 'f8c29d3ca28e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archives', sa.Column('owner', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('archives', 'owner')
    # ### end Alembic commands ###
