"""empty message

Revision ID: f8c29d3ca28e
Revises: 37ef59c4ac7b
Create Date: 2020-06-16 20:17:57.577306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8c29d3ca28e'
down_revision = '37ef59c4ac7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archives', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'archives', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'archives', type_='foreignkey')
    op.drop_column('archives', 'team_id')
    # ### end Alembic commands ###
